CREATE TABLE `online_business_application_location` (
  `objid` varchar(50) NOT NULL,
  `type` varchar(10) NOT NULL,
  `lessor_objid` varchar(50) DEFAULT NULL,
  `lessor_name` varchar(255) DEFAULT NULL,
  `lessor_address` varchar(255) DEFAULT NULL,
  `lessor_unitno` varchar(25) DEFAULT NULL,
  `lessor_location` varchar(255) DEFAULT NULL,
  `lessor_rent` decimal(16,2) DEFAULT NULL,
  `bldgname` varchar(100) DEFAULT NULL,
  `unitno` varchar(25) DEFAULT NULL,
  `street` varchar(150) DEFAULT NULL,
  `barangay` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`objid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;

create index ix_lessorid on online_business_application_location(lessor_objid)
;

CREATE TABLE `online_business_application_entity` (
  `objid` varchar(50) NOT NULL DEFAULT '',
	`appid` varchar(50) DEFAULT NULL,
  `profileid` varchar(50) DEFAULT NULL,
  `entitytype` varchar(50) DEFAULT NULL,
  `profileno` varchar(50) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `firstname` varchar(100) DEFAULT NULL,
  `middlename` varchar(100) DEFAULT NULL,
  `lastname` varchar(100) DEFAULT NULL,
  `birthdate` date DEFAULT NULL,
  `gender` varchar(1) DEFAULT NULL,
  `resident` int(255) DEFAULT NULL,
  `address_objid` varchar(50) DEFAULT NULL,
  `address_text` varchar(255) DEFAULT NULL,
  `address_unitno` varchar(50) DEFAULT NULL,
  `address_bldgno` varchar(50) DEFAULT NULL,
  `address_bldgname` varchar(100) DEFAULT NULL,
  `address_street` varchar(255) DEFAULT NULL,
  `address_subdivision` varchar(255) DEFAULT NULL,
  `address_barangay_objid` varchar(50) DEFAULT NULL,
  `address_barangay_name` varchar(50) DEFAULT NULL,
  `address_citymunicipality` varchar(50) DEFAULT NULL,
  `address_province` varchar(50) DEFAULT NULL,
  `tin` varchar(50) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `mobileno` varchar(50) DEFAULT NULL,
  `phoneno` varchar(50) DEFAULT NULL,
  `id` mediumtext,
  PRIMARY KEY (`objid`) USING BTREE,
  KEY `ix_profileid` (`profileid`),
  KEY `ix_profileno` (`profileno`),
  KEY `ix_name` (`name`),
  KEY `ix_addressid` (`address_objid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;

CREATE TABLE `online_business_application` (
  `objid` varchar(50) NOT NULL,
  `state` varchar(20) NOT NULL,
  `dtcreated` datetime NOT NULL,
  `createdby_objid` varchar(50) NOT NULL,
  `createdby_name` varchar(100) NOT NULL,
  `controlno` varchar(25) NOT NULL,
  `prevapplicationid` varchar(50) DEFAULT NULL,
  `business_objid` varchar(50) DEFAULT NULL,
  `appyear` int(11) NOT NULL,
  `apptype` varchar(20) NOT NULL,
  `appdate` date NOT NULL,
	`step` int(11) NOT NULL DEFAULT '0',
	`orgcode` varchar(50) NOT NULL,
	`partnername` varchar(50) NOT NULL,
	`tradename` varchar(255) DEFAULT NULL,
  `businessname` varchar(255) DEFAULT NULL,
  `businessaddress` varchar(255) DEFAULT NULL,
	`orgtype` varchar(10) DEFAULT NULL,
  `officetype` varchar(10) DEFAULT NULL,
  `branch` varchar(50) DEFAULT NULL,
  `lobs` text NOT NULL,
  `infos` longtext NOT NULL,
  `requirements` longtext NOT NULL,
	`attachments` text,
  `dtapproved` datetime DEFAULT NULL,
  `approvedby_objid` varchar(50) DEFAULT NULL,
  `approvedby_name` varchar(150) DEFAULT NULL,
  `approvedappno` varchar(25) DEFAULT NULL,
  `contact_name` varchar(255) NOT NULL,
  `contact_address` varchar(255) NOT NULL,
  `contact_email` varchar(255) NOT NULL,
  `contact_mobileno` varchar(15) DEFAULT NULL,
	`applicantid` varchar(50) DEFAULT NULL,
	`locationid` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`objid`),
  KEY `ix_state` (`state`),
  KEY `ix_dtcreated` (`dtcreated`),
  KEY `ix_controlno` (`controlno`),
  KEY `ix_prevapplicationid` (`prevapplicationid`),
  KEY `ix_business_objid` (`business_objid`),
  KEY `ix_appyear` (`appyear`),
  KEY `ix_appdate` (`appdate`),
  KEY `ix_dtapproved` (`dtapproved`),
  KEY `ix_approvedby_objid` (`approvedby_objid`),
  KEY `ix_approvedby_name` (`approvedby_name`),
  KEY `ix_businessname` (`businessname`),
  KEY `ix_applicantid` (`applicantid`),
  KEY `ix_locationid` (`locationid`),
  CONSTRAINT `fk_application_entity` FOREIGN KEY (`applicantid`) REFERENCES `online_business_application_entity` (`objid`),
  CONSTRAINT `fk_application_location` FOREIGN KEY (`locationid`) REFERENCES `online_business_application_location` (`objid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;

