version: "3"

services:

  jasper-server:
    container_name: jasper-server
    image: ramesesinc/jasper-server:1.0
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../_res/env.conf
      - ../_custom/env.conf
    ports:
      - "9088:8070"
    volumes:
      - ./connections:/apps/enterprise/connections
      - ./modules:/apps/enterprise/modules
      - ./templates:/apps/server/templates
      - ./output:/apps/server/output

      - ../_custom/reports:/apps/server/custom


  jasper-node-server:
    container_name: jasper-node-server
    image: ramesesinc/jasper-node-server:0.0.1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../_res/env.conf
      - ../_custom/env.conf
    ports:
      - "5005:5000"
    volumes:
      - ./connections/node:/apps/server/connections
      - ./output:/apps/server/reports

      - ../_custom/env.conf:/apps/server/_custom/env.conf
