version: "3"

services:
  cloud-fileserver:
    image: ramesesinc/cloud-fileserver:0.2.0
    container_name: cloud-fileserver
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    env_file:
      - ../_custom/env.conf
    environment:
      TZ: "Asia/Manila"
    ports:
      - "7000:7000"
