version: "3"

services:

  cloud-gdx-node:
    image: ramesesinc/cloud-gdx-node:1.2.1
    container_name: cloud-gdx-node
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    expose:
      - 3000
    ports:
      - "3000:3000"
    env_file:
      - ../_res/env.conf
      - ../_custom/env.conf
