version: "3"

services:

  cloud-epayment-server:
    image: ramesesinc/cloud-epayment-server:v004
    container_name: cloud-epayment-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../_res/env.conf
      - ../_custom/env.conf
    ports:
      - "9072:8070"
    volumes:
      - ./plugins:/apps/enterprise/plugins
      - ../_res/connections:/apps/enterprise/connections/ext
      - ../_custom/datasources/epaymentds:/services/datasources/mainds

      # report templates
      - ./templates/reports:/apps/server/templates/reports
      
      - ../_custom/jasper:/apps/server/templates/custom
      - ../_custom/output:/apps/server/output
