version: "3"

services:

  cloud-epayment-server:
    image: "ramesesinc/cloud-epayment-server:v003"
    container_name: cloud-epayment-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../_res/env.conf
      - ../_custom/env.conf
    ports:
      - "9072:8070"
    volumes:
      - ./modules:/apps/enterprise/modules
      - ../_res/connections:/apps/enterprise/connections/ext
      - ../_custom/datasources/epaymentds:/services/datasources/mainds

      # report templates
      - ./templates/reports:/apps/server/templates/reports
      
      - ../_custom/jasper:/apps/server/templates/custom
      - ../_custom/output:/apps/server/output

      - ../_res/lib/rameses-common2.jar:/apps/server/lib/rameses-common2.jar
      - ../_res/lib/rameses-main-bootloader.jar:/apps/server/lib/rameses-main-bootloader.jar
      - ../_res/lib/rameses-osiris3-core2.jar:/apps/server/lib/rameses-osiris3-core2.jar
      - ../_res/lib/rameses-osiris3-server.jar:/apps/server/lib/rameses-osiris3-server.jar
      - ../_res/lib/osiris2-report.jar:/apps/server/lib/osiris2-report.jar
      - ../_res/lib/jasperreports-3.0.0.jar:/apps/server/lib/jasperreports-3.0.0.jar
      - ../_res/lib/poi-3.0.1-FINAL-20070705.jar:/apps/server/lib/poi-3.0.1-FINAL-20070705.jar
      - ../_res/lib/png-encoder-1.5.jar:/apps/server/lib/png-encoder-1.5.jar
      - ../_res/lib/itextpdf-5.1.2.jar:/apps/server/lib/itextpdf-5.1.2.jar
      - ../_res/lib/itext-1.3.1.jar:/apps/server/lib/itext-1.3.1.jar
