version: "3"

services:

  cloud-epayment-server:
    image: "ramesesinc/cloud-epayment-server:v003"
    container_name: cloud-epayment-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../_res/env.conf
      - ../_custom/env.conf
    ports:
      - "9072:8070"
    volumes:
      - ./modules:/apps/enterprise/modules
      - ../_custom/datasources/epaymentds:/services/datasources/mainds

      - ../_res/lib/rameses-common2.jar:/apps/server/lib/rameses-common2.jar
      - ../_res/lib/rameses-main-bootloader.jar:/apps/server/lib/rameses-main-bootloader.jar
      - ../_res/lib/rameses-osiris3-core2.jar:/apps/server/lib/rameses-osiris3-core2.jar
      - ../_res/lib/rameses-osiris3-server.jar:/apps/server/lib/rameses-osiris3-server.jar

      - ./connections/partner:/services/apps/enterprise/connections/partner
