version: "3"

services:

  cloud-obo-server:
    image: "ramesesinc/cloud-obo-server:v003"
    container_name: cloud-obo-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../_res/env.conf
      - ../_custom/env.conf
    ports:
      - "10001:8070"
    volumes:
      - ./modules:/apps/enterprise/modules
      - ../_custom/datasources/obods:/services/datasources/mainds
