version: "3"

services:

  cloud-obo-server:
    image: "ramesesinc/cloud-obo-server:v001"
    container_name: cloud-obo-server
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../env.conf
    ports:
      - "10001:8070"
    volumes:
      - ./modules:/apps/server/services/apps/enterprise/modules
