version: "3"

services:

  cloud-partner-server:
    image: "ramesesinc/cloud-partner-server:v003"
    container_name: cloud-partner-server
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../_res/env.conf
      - ../_custom/env.conf
    ports:
      - "9071:8070"
    volumes:
      - ./modules:/apps/enterprise/modules

      - ../_custom/datasources/partnerds:/services/datasources/mainds

      - ./_dev/connections:/apps/enterprise/connections
      - ./_dev/lib/rameses-common2.jar:/apps/server/lib/rameses-common2.jar
      - ./_dev/lib/rameses-main-bootloader.jar:/apps/server/lib/rameses-main-bootloader.jar
      - ./_dev/lib/rameses-osiris3-core2.jar:/apps/server/lib/rameses-osiris3-core2.jar
      - ./_dev/lib/rameses-osiris3-server.jar:/apps/server/lib/rameses-osiris3-server.jar
