version: "3"

services:

  cloud-proxy-server:
    image: nginx:latest
    container_name: cloud-proxy-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    ports:
      - "80:80"
    volumes:
      - ../res:/res
      - ../conf.d:/etc/nginx/conf.d
