version: "3"

services:
  filipizen-sveltekit:
    image: "ramesesinc/cloud-filipizen-sveltekit:0.1.0"
    container_name: cloud-filipizen-sveltekit
    env_file:
      - ./env.conf
    ports:
      - "5001:3000"
