version: "3"

services:

  cloud-proxy-server:
    image: nginx:latest
    container_name: cloud-proxy-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../env.conf
      - ../_custom/env.conf
    ports:
      - "80:80"
    volumes:
      - ../nginx/res:/res
      - ../nginx/_src:/_src
      - ../nginx/_src/conf.d:/etc/nginx/conf.d
      - ../nginx/_src/nginx.conf:/etc/nginx/nginx.conf
    command: ["sh", "/_src/scripts/run.sh" ]


  filipizen-web:
    image: "ramesesinc/filipizen-web:v001"
    container_name: filipizen-web
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../env.conf
      - ../_custom/env.conf
    ports:
      - "9080:8080"
    volumes:
      - ./modules:/apps/server/modules
      - ./webroot:/apps/server/webroot
