version: "3"

services:

  filipizen-web:
    image: "ramesesinc/filipizen-web:v001"
    container_name: filipizen-web
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../env.conf
      - ../_custom/env.conf
    ports:
      - "9080:8080"
    volumes:
      - ./modules:/apps/server/modules
      - ./webroot:/apps/server/webroot
