version: "3"

services:

  cloud-redis:
    image: redis:5.0.6
    container_name: cloud-redis
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ./data:/data
    expose: 
      - 6379
    ports:
      - "6379:6379"
